# Generated by Django 4.1.1 on 2022-11-16 01:09

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='info',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='relesed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
