# Generated by Django 4.1.1 on 2022-11-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_relesed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='relesed_date',
        ),
    ]
