# Generated by Django 4.1.1 on 2022-11-16 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_relesed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='released_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 16, 1, 19, 20, 667960)),
        ),
    ]
