# Generated by Django 4.1.1 on 2022-11-16 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 16, 1, 20, 51, 593953), null=True),
        ),
    ]
