# Generated by Django 4.1.1 on 2022-11-30 08:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0012_movie_gifs_alter_movie_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 30, 8, 16, 45, 978901), null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.IntegerField()),
                ('reviewText', models.CharField(max_length=200)),
                ('movieId', models.ForeignKey(db_column='movieId', on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.movie')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
