# Generated by Django 4.1.1 on 2022-12-04 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_released_date_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 4, 8, 10, 58, 4914), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='movieId',
            field=models.ForeignKey(db_column='movieId', on_delete=django.db.models.deletion.CASCADE, related_name='movieid', to='movies.movie'),
        ),
    ]
